# Generated by Django 3.2.9 on 2023-01-31 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=250)),
                ('shortened_url', models.URLField(max_length=30)),
                ('shortened_url_code', models.CharField(max_length=20, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_on'],
                'unique_together': {('original_url', 'shortened_url')},
            },
        ),
    ]
