# Generated by Django 3.2.9 on 2023-01-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_urlshortener_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='urlshortener',
            unique_together={('original_url', 'shortened_url')},
        ),
    ]
