# Generated by Django 3.2.9 on 2023-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_urlshortener_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.CharField(max_length=30),
        ),
    ]
