# Generated by Django 3.2.9 on 2023-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_urlshortener_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='original_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.URLField(max_length=30),
        ),
    ]
