# Generated by Django 3.2.9 on 2023-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20230131_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.URLField(max_length=30, unique=True),
        ),
    ]
