# Generated by Django 3.2.9 on 2023-02-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_alter_urlshortener_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='original_url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
